apiVersion: apps/v1
kind: Deployment
metadata:
  name: kopf-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kopf-controller
  template:
    metadata:
      labels:
        run: kopf-controller
    spec:
      containers:
      - name: kopf-controller
        image: iamkashz/angi-controller:latest
